/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hui.chen' at '10/28/16 4:28 PM' with Gradle 3.1
 *
 * @author hui.chen, @date 10/28/16 4:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
